apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: password

---
apiVersion: v1
kind: Secret
metadata:
  name: stationery-backend-secret
type: Opaque
stringData:
  DATABASE_HOST: mongodb-0.mongodb #inject from statefulset service
  DATABASE_SCHEMA: simple-stationery-crud
  DATABASE_USER: root
  DATABASE_PASSWORD: password
  DATABASE_PORT: "27017"